;;; terraform-mode-test.el --- Tests for terraform-mode -*- lexical-binding: t -*-

;;; Commentary:
;; ERT tests for terraform-mode.

;;; Code:

(require 'ert)
(require 'terraform-mode)

;;; Helpers

(defmacro terraform-test-with-buffer (content &rest body)
  "Run BODY in a temp buffer with CONTENT in terraform-mode."
  (declare (indent 1))
  `(with-temp-buffer
     (terraform-mode)
     (insert ,content)
     (font-lock-ensure)
     ,@body))

(defun terraform-test-comment-p (pos)
  "Return non-nil if POS is inside a comment."
  (nth 4 (syntax-ppss pos)))

(defun terraform-test-string-p (pos)
  "Return non-nil if POS is inside a string."
  (nth 3 (syntax-ppss pos)))

(defun terraform-test-text-property (description content checks)
  "Assert text properties in a terraform-mode buffer with CONTENT.
DESCRIPTION is used in failure messages.
CHECKS is a list of alists, each with pos, property, and value keys."
  (with-temp-buffer
    (terraform-mode)
    (insert content)
    (font-lock-ensure)
    (dolist (check checks)
      (let ((pos      (alist-get 'pos check))
            (property (alist-get 'property check))
            (expected (alist-get 'value check)))
        (unless (eq (get-text-property pos property) expected)
          (ert-fail (format "%s: expected %S=%S at pos %d, got %S"
                            description property expected pos
                            (get-text-property pos property))))))))

(defun terraform-test-face (description content checks)
  "Assert face properties in a terraform-mode buffer with CONTENT.
DESCRIPTION is used in failure messages.
CHECKS is a list of alists, each with pos and face keys."
  (with-temp-buffer
    (terraform-mode)
    (insert content)
    (font-lock-ensure)
    (dolist (check checks)
      (let ((pos (alist-get 'pos check))
            (expected (alist-get 'face check)))
        (unless (eq (get-text-property pos 'face) expected)
          (ert-fail (format "%s: expected face %S at pos %d, got %S"
                            description expected pos
                            (get-text-property pos 'face))))))))

;;; Mode activation

(ert-deftest terraform-mode-auto-mode-tf ()
  "terraform-mode activates for .tf files."
  (should (equal (cdr (assoc "\\.tf\\'" auto-mode-alist)) 'terraform-mode)))

(ert-deftest terraform-mode-auto-mode-tfvars ()
  "terraform-mode activates for .tfvars files."
  (should (equal (cdr (assoc "\\.tfvars\\'" auto-mode-alist)) 'terraform-mode)))

(ert-deftest terraform-mode-auto-mode-tofu ()
  "terraform-mode activates for .tofu files."
  (should (equal (cdr (assoc "\\.tofu\\'" auto-mode-alist)) 'terraform-mode)))

;;; Comment syntax

(ert-deftest terraform-mode-hash-comment ()
  "# starts a line comment."
  (terraform-test-with-buffer "# comment"
    (should (terraform-test-comment-p 3))))

(ert-deftest terraform-mode-hash-comment-ends-at-newline ()
  "# comment ends at newline."
  (terraform-test-with-buffer "# comment\nnot-a-comment"
    (should (terraform-test-comment-p 3))
    (should-not (terraform-test-comment-p 11))))

(ert-deftest terraform-mode-double-slash-comment ()
  "// starts a line comment."
  (terraform-test-with-buffer "// comment"
    (should (terraform-test-comment-p 4))))

(ert-deftest terraform-mode-double-slash-comment-ends-at-newline ()
  "// comment ends at newline."
  (terraform-test-with-buffer "// comment\nnot-a-comment"
    (should (terraform-test-comment-p 4))
    (should-not (terraform-test-comment-p 12))))

(ert-deftest terraform-mode-block-comment ()
  "/* */ is a block comment."
  (terraform-test-with-buffer "/* comment */"
    (should (terraform-test-comment-p 4))))

(ert-deftest terraform-mode-block-comment-multiline ()
  "/* */ block comment spans multiple lines."
  (terraform-test-with-buffer "/*\ncomment\n*/"
    (should (terraform-test-comment-p 3))
    (should (terraform-test-comment-p 5))))

;;; String syntax

(ert-deftest terraform-mode-string ()
  "Double-quoted string is recognized."
  (terraform-test-with-buffer "\"hello\""
    (should (terraform-test-string-p 2))))

(ert-deftest terraform-mode-string-ends ()
  "String ends at closing quote."
  (terraform-test-with-buffer "\"hello\" world"
    (should (terraform-test-string-p 2))
    (should-not (terraform-test-string-p 9))))

;;; String interpolation syntax

(ert-deftest terraform-mode-string-interpolation ()
  "Content inside ${...} is not parsed as a string."
  ;; "${var.foo}" - positions: "(1)$(2){(3)v(4)a(5)r(6).(7)f(8)o(9)o(10)}(11)"(12)
  (terraform-test-with-buffer "\"${var.foo}\""
    (should-not (terraform-test-string-p 4))))

(ert-deftest terraform-mode-string-interpolation-literal-part ()
  "Content outside ${...} in a string is still parsed as a string."
  ;; "prefix-${var.foo}" - 'p' at pos 2 is in the literal part
  (terraform-test-with-buffer "\"prefix-${var.foo}\""
    (should (terraform-test-string-p 2))
    (should-not (terraform-test-string-p 11))))

(ert-deftest terraform-mode-string-interpolation-escaped ()
  "$\\${ is not treated as an interpolation."
  ;; "$${literal}" - the $$ escapes the interpolation
  (terraform-test-with-buffer "\"$${literal}\""
    (should (terraform-test-string-p 5))))

;;; Heredoc syntax

(ert-deftest test-terraform-mode--heredoc ()
  (dolist (case '(((description . "heredoc content gets string face")
                   (content     . "<<EOF\nhello\nEOF\n")
                   (check       . (((pos . 7) (face . font-lock-string-face)))))
                  ((description . "indent-strip heredoc content gets string face")
                   (content     . "<<-EOF\n  hello\n  EOF\n")
                   (check       . (((pos . 10) (face . font-lock-string-face)))))
                  ((description . "incomplete heredoc content gets string face")
                   (content     . "<<EOF\nhello")
                   (check       . (((pos . 7) (face . font-lock-string-face)))))
                  ((description . "content after heredoc closer gets no string face")
                   (content     . "<<EOF\nhello\nEOF\nafter")
                   (check       . (((pos . 17) (face . nil)))))
                  ((description . "non-strip heredoc with indented closer is recognized")
                   (content     . "<<EOF\nhello\n  EOF\nafter")
                   (check       . (((pos . 19) (face . nil)))))
                  ((description . "interpolation content inside heredoc gets no string face")
                   (content     . "<<EOF\n${var}\nEOF\n")
                   (check       . (((pos . 9) (face . nil)))))))
    (terraform-test-face (alist-get 'description case)
                         (alist-get 'content case)
                         (alist-get 'check case))))

;;; Bracket syntax

(ert-deftest terraform-mode-curly-brackets ()
  "Curly braces are matched pairs."
  (terraform-test-with-buffer "{}"
    (goto-char 1)
    (should (equal (char-before (scan-sexps 1 1)) ?}))))

(ert-deftest terraform-mode-square-brackets ()
  "Square brackets are matched pairs."
  (terraform-test-with-buffer "[]"
    (goto-char 1)
    (should (equal (char-before (scan-sexps 1 1)) ?\]))))

(ert-deftest terraform-mode-parens ()
  "Parentheses are matched pairs."
  (terraform-test-with-buffer "()"
    (goto-char 1)
    (should (equal (char-before (scan-sexps 1 1)) ?\)))))

;;; Font-lock

(ert-deftest test-terraform-mode--match-depth-0-builtin ()
  (dolist (case '(((description . "terraform at depth 0")
                   (content     . "terraform {}")
                   (check       . (((pos . 1) (face . font-lock-builtin-face)))))
                  ((description . "terraform indented at depth 0")
                   (content     . "  terraform {}")
                   (check       . (((pos . 3) (face . font-lock-builtin-face)))))
                  ((description . "terraform at depth 1 gets no builtin face")
                   (content     . "resource \"foo\" \"bar\" {\nterraform {}\n}")
                   (check       . (((pos . 23) (face . nil)))))))
    (terraform-test-face (alist-get 'description case)
                         (alist-get 'content case)
                         (alist-get 'check case))))

(ert-deftest test-terraform-mode--match-inside-terraform-block ()
  (dolist (case '(((description . "required_providers inside terraform block")
                   (content     . "terraform {\nrequired_providers {}\n}")
                   (check       . (((pos . 13) (face . font-lock-builtin-face)))))
                  ((description . "cloud inside terraform block")
                   (content     . "terraform {\ncloud {}\n}")
                   (check       . (((pos . 13) (face . font-lock-builtin-face)))))
                  ((description . "workspaces inside terraform block")
                   (content     . "terraform {\ncloud {\nworkspaces {}\n}\n}")
                   (check       . (((pos . 21) (face . font-lock-builtin-face)))))
                  ((description . "required_providers outside terraform block gets no builtin face")
                   (content     . "required_providers {}")
                   (check       . (((pos . 1) (face . nil)))))
                  ((description . "cloud outside terraform block gets no builtin face")
                   (content     . "cloud {}")
                   (check       . (((pos . 1) (face . nil)))))))
    (terraform-test-face (alist-get 'description case)
                         (alist-get 'content case)
                         (alist-get 'check case))))

(ert-deftest test-terraform-mode--assignment ()
  (dolist (case '(((description . "assignment target inside locals block")
                   (content     . "locals {\nthis_is_a_variable = \"some value\"\n}")
                   (check       . (((pos . 10) (face . font-lock-variable-name-face)))))
                  ((description . "indented assignment target inside locals block")
                   (content     . "locals {\n  this_is_a_variable = \"some value\"\n}")
                   (check       . (((pos . 12) (face . font-lock-variable-name-face)))))
                  ((description . "first key in inline map gets variable-name face")
                   (content     . "locals {\nfoo = {test = \"bar\", baz = 123}\n}")
                   (check       . (((pos . 17) (face . font-lock-variable-name-face)))))
                  ((description . "second key in inline map gets variable-name face")
                   (content     . "locals {\nfoo = {test = \"bar\", baz = 123}\n}")
                   (check       . (((pos . 31) (face . font-lock-variable-name-face)))))
                  ((description . "assignment outside any block gets no face")
                   (content     . "this_is_a_variable = \"some value\"")
                   (check       . (((pos . 1) (face . nil)))))))
    (terraform-test-face (alist-get 'description case)
                         (alist-get 'content case)
                         (alist-get 'check case))))

(ert-deftest test-terraform-mode--match-provider ()
  (dolist (case '(((description . "single provider inside required_providers")
                   (content     . "terraform {\nrequired_providers {\naws {\n}\n}\n}")
                   (check       . (((pos . 34) (face . font-lock-type-face)))))
                  ((description . "multiple providers inside required_providers")
                   (content     . "terraform {\nrequired_providers {\naws {\n}\nazure {\n}\n}\n}")
                   (check       . (((pos . 34) (face . font-lock-type-face))
                                   ((pos . 42) (face . font-lock-type-face)))))
                  ((description . "provider outside required_providers gets no type face")
                   (content     . "aws {}")
                   (check       . (((pos . 1) (face . nil)))))))
    (terraform-test-face (alist-get 'description case)
                         (alist-get 'content case)
                         (alist-get 'check case))))

(ert-deftest test-terraform-mode--block-builtins-with-type ()
  (dolist (case '(((description . "backend keyword and type")
                   (content     . "backend \"s3\" {}")
                   (check       . (((pos . 1) (face . font-lock-builtin-face))
                                   ((pos . 9) (face . font-lock-type-face)))))
                  ((description . "provider_meta keyword and type")
                   (content     . "provider_meta \"foo\" {}")
                   (check       . (((pos . 1)  (face . font-lock-builtin-face))
                                   ((pos . 15) (face . font-lock-type-face)))))
                  ((description . "variable keyword and name")
                   (content     . "variable \"foo\" {}")
                   (check       . (((pos . 1)  (face . font-lock-builtin-face))
                                   ((pos . 10) (face . font-lock-variable-name-face)))))
                  ((description . "provisioner keyword and type inside resource block")
                   (content     . "resource \"aws_instance\" \"web\" {\nprovisioner \"local-exec\" {}\n}")
                   (check       . (((pos . 33) (face . font-lock-builtin-face))
                                   ((pos . 45) (face . font-lock-type-face)))))
                  ((description . "builtin-with-type in block comment gets comment face")
                   (content     . "/* backend \"s3\" {} */")
                   (check       . (((pos . 4) (face . font-lock-comment-face)))))))
    (terraform-test-face (alist-get 'description case)
                         (alist-get 'content case)
                         (alist-get 'check case))))

(ert-deftest test-terraform-mode--terraform-block ()
  (dolist (case '(((description . "content inside terraform block has property")
                   (content     . "terraform {\nrequired_version = \"1.0\"\n}")
                   (check       . (((pos . 13) (property . terraform-mode-terraform-block) (value . t)))))
                  ((description . "content outside terraform block has no property")
                   (content     . "required_version = \"1.0\"")
                   (check       . (((pos . 1) (property . terraform-mode-terraform-block) (value . nil)))))))
    (terraform-test-text-property (alist-get 'description case)
                                  (alist-get 'content case)
                                  (alist-get 'check case))))

(ert-deftest test-terraform-mode--locals-block ()
  (dolist (case '(((description . "content inside locals block has property")
                   (content     . "locals {\nfoo = 1\n}")
                   (check       . (((pos . 10) (property . terraform-mode-locals-block) (value . t)))))
                  ((description . "content outside locals block has no property")
                   (content     . "foo = 1")
                   (check       . (((pos . 1) (property . terraform-mode-locals-block) (value . nil)))))))
    (terraform-test-text-property (alist-get 'description case)
                                  (alist-get 'content case)
                                  (alist-get 'check case))))

(ert-deftest test-terraform-mode--locals-keyword ()
  (dolist (case '(((description . "locals keyword gets builtin face")
                   (content     . "locals {}")
                   (check       . (((pos . 1) (face . font-lock-builtin-face)))))))
    (terraform-test-face (alist-get 'description case)
                         (alist-get 'content case)
                         (alist-get 'check case))))

(ert-deftest test-terraform-mode--variable-block ()
  (dolist (case '(((description . "content inside variable block has property")
                   (content     . "variable \"foo\" {\ndefault = 1\n}")
                   (check       . (((pos . 18) (property . terraform-mode-variable-block) (value . t)))))
                  ((description . "content outside variable block has no property")
                   (content     . "default = 1")
                   (check       . (((pos . 1) (property . terraform-mode-variable-block) (value . nil)))))
                  ((description . "variable block nested at depth 1 has no property")
                   (content     . "resource \"aws_instance\" \"foo\" {\nvariable \"bar\" {\ndefault = 1\n}\n}")
                   (check       . (((pos . 48) (property . terraform-mode-variable-block) (value . nil)))))))
    (terraform-test-text-property (alist-get 'description case)
                                  (alist-get 'content case)
                                  (alist-get 'check case))))

(ert-deftest test-terraform-mode--required-providers-block ()
  (dolist (case '(((description . "content inside required_providers block has property")
                   (content     . "terraform {\nrequired_providers {\naws = {}\n}\n}")
                   (check       . (((pos . 33) (property . terraform-mode-required-providers) (value . t)))))
                  ((description . "required_providers outside terraform block has no property")
                   (content     . "required_providers {\naws = {}\n}")
                   (check       . (((pos . 21) (property . terraform-mode-required-providers) (value . nil)))))))
    (terraform-test-text-property (alist-get 'description case)
                                  (alist-get 'content case)
                                  (alist-get 'check case))))

(ert-deftest test-terraform-mode--match-variable-type ()
  (dolist (case '(((description . "string type inside variable block")
                   (content     . "variable \"foo\" {\ntype = string\n}")
                   (check       . (((pos . 25) (face . font-lock-type-face)))))
                  ((description . "number type inside variable block")
                   (content     . "variable \"foo\" {\ntype = number\n}")
                   (check       . (((pos . 25) (face . font-lock-type-face)))))
                  ((description . "bool type inside variable block")
                   (content     . "variable \"foo\" {\ntype = bool\n}")
                   (check       . (((pos . 25) (face . font-lock-type-face)))))
                  ((description . "list type inside variable block")
                   (content     . "variable \"foo\" {\ntype = list(string)\n}")
                   (check       . (((pos . 25) (face . font-lock-type-face)))))
                  ((description . "bare list inside variable block gets variable face not type face")
                   (content     . "variable \"foo\" {\nlist = 1\n}")
                   (check       . (((pos . 18) (face . font-lock-variable-name-face)))))
                  ((description . "set type inside variable block")
                   (content     . "variable \"foo\" {\ntype = set(number)\n}")
                   (check       . (((pos . 25) (face . font-lock-type-face)))))
                  ((description . "map type inside variable block")
                   (content     . "variable \"foo\" {\ntype = map(string)\n}")
                   (check       . (((pos . 25) (face . font-lock-type-face)))))
                  ((description . "object type inside variable block")
                   (content     . "variable \"foo\" {\ntype = object({ name = string })\n}")
                   (check       . (((pos . 25) (face . font-lock-type-face)))))
                  ((description . "list( partial type inside variable block")
                   (content     . "variable \"foo\" {\ntype = list(\n}")
                   (check       . (((pos . 25) (face . font-lock-type-face)))))
                  ((description . "set( partial type inside variable block")
                   (content     . "variable \"foo\" {\ntype = set(\n}")
                   (check       . (((pos . 25) (face . font-lock-type-face)))))
                  ((description . "map( partial type inside variable block")
                   (content     . "variable \"foo\" {\ntype = map(\n}")
                   (check       . (((pos . 25) (face . font-lock-type-face)))))
                  ((description . "object( partial type inside variable block")
                   (content     . "variable \"foo\" {\ntype = object(\n}")
                   (check       . (((pos . 25) (face . font-lock-type-face)))))
                  ((description . "type keyword outside variable block gets no type face")
                   (content     . "string")
                   (check       . (((pos . 1) (face . nil)))))))
    (terraform-test-face (alist-get 'description case)
                         (alist-get 'content case)
                         (alist-get 'check case))))

(ert-deftest test-terraform-mode--match-variable-type-builtins ()
  (dolist (case '(((description . "true inside variable block")
                   (content     . "variable \"foo\" {\ndefault = true\n}")
                   (check       . (((pos . 28) (face . font-lock-constant-face)))))
                  ((description . "false inside variable block")
                   (content     . "variable \"foo\" {\ndefault = false\n}")
                   (check       . (((pos . 28) (face . font-lock-constant-face)))))
                  ((description . "optional inside variable block")
                   (content     . "variable \"foo\" {\ntype = object({ name = optional(string) })\n}")
                   (check       . (((pos . 41) (face . font-lock-builtin-face)))))
                  ((description . "optional outside variable block gets no builtin face")
                   (content     . "optional")
                   (check       . (((pos . 1) (face . nil)))))))
    (terraform-test-face (alist-get 'description case)
                         (alist-get 'content case)
                         (alist-get 'check case))))

(ert-deftest test-terraform-mode--resource-block ()
  (dolist (case '(((description . "content inside resource block has property")
                   (content     . "resource \"aws_instance\" \"foo\" {\nami = \"abc\"\n}")
                   (check       . (((pos . 33) (property . terraform-mode-resource-block) (value . t)))))
                  ((description . "content inside data block has property")
                   (content     . "data \"aws_ami\" \"foo\" {\nowners = [\"self\"]\n}")
                   (check       . (((pos . 24) (property . terraform-mode-resource-block) (value . t)))))
                  ((description . "content outside resource block has no property")
                   (content     . "ami = \"abc\"")
                   (check       . (((pos . 1) (property . terraform-mode-resource-block) (value . nil)))))))
    (terraform-test-text-property (alist-get 'description case)
                                  (alist-get 'content case)
                                  (alist-get 'check case))))

(ert-deftest test-terraform-mode--block-builtins-with-type-and-name ()
  (dolist (case '(((description . "resource keyword gets builtin face")
                   (content     . "resource \"aws_instance\" \"foo\" {}")
                   (check       . (((pos . 1) (face . font-lock-builtin-face)))))
                  ((description . "resource type gets type face")
                   (content     . "resource \"aws_instance\" \"foo\" {}")
                   (check       . (((pos . 10) (face . font-lock-type-face)))))
                  ((description . "resource name gets variable-name face")
                   (content     . "resource \"aws_instance\" \"foo\" {}")
                   (check       . (((pos . 25) (face . font-lock-variable-name-face)))))
                  ((description . "data keyword gets builtin face")
                   (content     . "data \"aws_ami\" \"foo\" {}")
                   (check       . (((pos . 1) (face . font-lock-builtin-face)))))
                  ((description . "data type gets type face")
                   (content     . "data \"aws_ami\" \"foo\" {}")
                   (check       . (((pos . 6) (face . font-lock-type-face)))))
                  ((description . "data name gets variable-name face")
                   (content     . "data \"aws_ami\" \"foo\" {}")
                   (check       . (((pos . 16) (face . font-lock-variable-name-face)))))))
    (terraform-test-face (alist-get 'description case)
                         (alist-get 'content case)
                         (alist-get 'check case))))

(ert-deftest test-terraform-mode--block-keywords-progressive ()
  (dolist (case '(((description . "terraform keyword alone gets builtin face")
                   (content     . "terraform")
                   (check       . (((pos . 1) (face . font-lock-builtin-face)))))
                  ((description . "resource keyword alone gets builtin face")
                   (content     . "resource")
                   (check       . (((pos . 1) (face . font-lock-builtin-face)))))
                  ((description . "data keyword alone gets builtin face")
                   (content     . "data")
                   (check       . (((pos . 1) (face . font-lock-builtin-face)))))
                  ((description . "variable keyword alone gets builtin face")
                   (content     . "variable")
                   (check       . (((pos . 1) (face . font-lock-builtin-face)))))
                  ((description . "resource with type label but no name or brace gets type face")
                   (content     . "resource \"aws_instance\"")
                   (check       . (((pos . 10) (face . font-lock-type-face)))))
                  ((description . "variable with name but no brace gets variable-name face")
                   (content     . "variable \"my_var\"")
                   (check       . (((pos . 10) (face . font-lock-variable-name-face)))))
                  ((description . "resource with both labels but no brace gets variable-name face on name")
                   (content     . "resource \"aws_instance\" \"my_ec2\"")
                   (check       . (((pos . 25) (face . font-lock-variable-name-face)))))))
    (terraform-test-face (alist-get 'description case)
                         (alist-get 'content case)
                         (alist-get 'check case))))

(ert-deftest test-terraform-mode--resource-sub-block ()
  (dolist (case '(((description . "sub-block label inside resource block gets variable-name face")
                   (content     . "resource \"aws_instance\" \"foo\" {\nvpc_settings {\n}\n}")
                   (check       . (((pos . 33) (face . font-lock-variable-name-face)))))
                  ((description . "lifecycle inside resource block gets builtin face not variable-name face")
                   (content     . "resource \"aws_instance\" \"foo\" {\nlifecycle {\n}\n}")
                   (check       . (((pos . 33) (face . font-lock-builtin-face)))))
                  ((description . "sub-block outside resource block gets no variable-name face")
                   (content     . "vpc_settings {}")
                   (check       . (((pos . 1) (face . nil)))))))
    (terraform-test-face (alist-get 'description case)
                         (alist-get 'content case)
                         (alist-get 'check case))))

(ert-deftest test-terraform-mode--lifecycle ()
  (dolist (case '(((description . "lifecycle inside resource block gets builtin face")
                   (content     . "resource \"aws_instance\" \"foo\" {\nlifecycle {\n}\n}")
                   (check       . (((pos . 33) (face . font-lock-builtin-face)))))
                  ((description . "lifecycle outside resource block gets no builtin face")
                   (content     . "lifecycle {}")
                   (check       . (((pos . 1) (face . nil)))))
                  ((description . "validation inside variable block gets builtin face")
                   (content     . "variable \"foo\" {\nvalidation {\n}\n}")
                   (check       . (((pos . 18) (face . font-lock-builtin-face)))))
                  ((description . "validation outside variable block gets no builtin face")
                   (content     . "validation {}")
                   (check       . (((pos . 1) (face . nil)))))
                  ((description . "connection inside resource block gets builtin face")
                   (content     . "resource \"aws_instance\" \"foo\" {\nconnection {\n}\n}")
                   (check       . (((pos . 33) (face . font-lock-builtin-face)))))
                  ((description . "connection outside resource block gets no builtin face")
                   (content     . "connection {}")
                   (check       . (((pos . 1) (face . nil)))))))
    (terraform-test-face (alist-get 'description case)
                         (alist-get 'content case)
                         (alist-get 'check case))))

(ert-deftest test-terraform-mode--each ()
  (dolist (case '(((description . "each.key inside resource block gets builtin face on each")
                   (content     . "resource \"aws_instance\" \"foo\" {\neach.key\n}")
                   (check       . (((pos . 33) (face . font-lock-builtin-face)))))
                  ((description . "each.key inside resource block gets builtin face on key")
                   (content     . "resource \"aws_instance\" \"foo\" {\neach.key\n}")
                   (check       . (((pos . 38) (face . font-lock-builtin-face)))))
                  ((description . "each.value inside resource block gets builtin face on value")
                   (content     . "resource \"aws_instance\" \"foo\" {\neach.value\n}")
                   (check       . (((pos . 38) (face . font-lock-builtin-face)))))
                  ((description . "each alone inside resource block gets builtin face")
                   (content     . "resource \"aws_instance\" \"foo\" {\neach\n}")
                   (check       . (((pos . 33) (face . font-lock-builtin-face)))))
                  ((description . "each.key outside resource block gets no builtin face")
                   (content     . "each.key")
                   (check       . (((pos . 1) (face . nil)))))))
    (terraform-test-face (alist-get 'description case)
                         (alist-get 'content case)
                         (alist-get 'check case))))

(ert-deftest test-terraform-mode--module-block ()
  (dolist (case '(((description . "content inside module block has property")
                   (content     . "module \"vpc\" {\nsource = \"terraform-aws-vpc\"\n}")
                   (check       . (((pos . 16) (property . terraform-mode-module-block) (value . t)))))
                  ((description . "content outside module block has no property")
                   (content     . "source = \"terraform-aws-vpc\"")
                   (check       . (((pos . 1) (property . terraform-mode-module-block) (value . nil)))))
                  ((description . "module block nested at depth 1 has no property")
                   (content     . "resource \"aws_instance\" \"foo\" {\nmodule \"vpc\" {\nsource = \"x\"\n}\n}")
                   (check       . (((pos . 48) (property . terraform-mode-module-block) (value . nil)))))))
    (terraform-test-text-property (alist-get 'description case)
                                  (alist-get 'content case)
                                  (alist-get 'check case))))

(ert-deftest test-terraform-mode--output-block ()
  (dolist (case '(((description . "content inside output block has property")
                   (content     . "output \"vpc_id\" {\nvalue = module.vpc.vpc_id\n}")
                   (check       . (((pos . 18) (property . terraform-mode-output-block) (value . t)))))
                  ((description . "content outside output block has no property")
                   (content     . "value = \"x\"")
                   (check       . (((pos . 1) (property . terraform-mode-output-block) (value . nil)))))
                  ((description . "output block nested at depth 1 has no property")
                   (content     . "resource \"aws_instance\" \"foo\" {\noutput \"id\" {\nvalue = 1\n}\n}")
                   (check       . (((pos . 46) (property . terraform-mode-output-block) (value . nil)))))))
    (terraform-test-text-property (alist-get 'description case)
                                  (alist-get 'content case)
                                  (alist-get 'check case))))

(ert-deftest test-terraform-mode--module-builtins ()
  (dolist (case '(((description . "source inside module block gets builtin face")
                   (content     . "module \"vpc\" {\nsource = \"terraform-aws-vpc\"\n}")
                   (check       . (((pos . 16) (face . font-lock-builtin-face)))))
                  ((description . "providers inside module block gets builtin face")
                   (content     . "module \"vpc\" {\nproviders = {}\n}")
                   (check       . (((pos . 16) (face . font-lock-builtin-face)))))))
    (terraform-test-face (alist-get 'description case)
                         (alist-get 'content case)
                         (alist-get 'check case))))

(ert-deftest test-terraform-mode--builtin-functions ()
  (dolist (case '(((description . "merge gets builtin face inside locals block")
                   (content     . "locals {\nmerge(var.a, var.b)\n}")
                   (check       . (((pos . 10) (face . font-lock-builtin-face)))))
                  ((description . "tostring gets builtin face inside locals block")
                   (content     . "locals {\ntostring(42)\n}")
                   (check       . (((pos . 10) (face . font-lock-builtin-face)))))
                  ((description . "function name without parens gets no builtin face")
                   (content     . "locals {\nmerge\n}")
                   (check       . (((pos . 10) (face . nil)))))
                  ((description . "function call outside any block gets no builtin face")
                   (content     . "merge(var.a, var.b)")
                   (check       . (((pos . 1) (face . nil)))))))
    (terraform-test-face (alist-get 'description case)
                         (alist-get 'content case)
                         (alist-get 'check case))))


(ert-deftest test-terraform-mode--literal-keywords ()
  (dolist (case '(((description . "true inside locals block gets constant face")
                   (content     . "locals {\ntrue\n}")
                   (check       . (((pos . 10) (face . font-lock-constant-face)))))
                  ((description . "false inside locals block gets constant face")
                   (content     . "locals {\nfalse\n}")
                   (check       . (((pos . 10) (face . font-lock-constant-face)))))
                  ((description . "true inside resource block gets constant face")
                   (content     . "resource \"aws_instance\" \"foo\" {\ndelete_on_termination = true\n}")
                   (check       . (((pos . 57) (face . font-lock-constant-face)))))
                  ((description . "false inside resource block gets constant face")
                   (content     . "resource \"aws_instance\" \"foo\" {\ndelete_on_termination = false\n}")
                   (check       . (((pos . 57) (face . font-lock-constant-face)))))
                  ((description . "null inside locals block gets constant face")
                   (content     . "locals {\nnull\n}")
                   (check       . (((pos . 10) (face . font-lock-constant-face)))))
                  ((description . "true outside any block gets no face")
                   (content     . "true")
                   (check       . (((pos . 1) (face . nil)))))))
    (terraform-test-face (alist-get 'description case)
                         (alist-get 'content case)
                         (alist-get 'check case))))

(ert-deftest test-terraform-mode--reference-keywords ()
  (dolist (case '(((description . "var gets builtin face inside resource block")
                   (content     . "resource \"r\" \"n\" {\nvar.instance_type\n}")
                   (check       . (((pos . 21) (face . font-lock-builtin-face)))))
                  ((description . "local gets builtin face inside resource block")
                   (content     . "resource \"r\" \"n\" {\nlocal.common_tags\n}")
                   (check       . (((pos . 21) (face . font-lock-builtin-face)))))
                  ((description . "module reference gets builtin face inside resource block")
                   (content     . "resource \"r\" \"n\" {\nmodule.vpc.vpc_id\n}")
                   (check       . (((pos . 21) (face . font-lock-builtin-face)))))
                  ((description . "data reference gets builtin face inside resource block")
                   (content     . "resource \"r\" \"n\" {\ndata.aws_ami.ubuntu.id\n}")
                   (check       . (((pos . 21) (face . font-lock-builtin-face)))))
                  ((description . "self reference gets builtin face inside resource block")
                   (content     . "resource \"r\" \"n\" {\nself.public_ip\n}")
                   (check       . (((pos . 21) (face . font-lock-builtin-face)))))
                  ((description . "var outside any block gets no face")
                   (content     . "var.instance_type")
                   (check       . (((pos . 1) (face . nil)))))))
    (terraform-test-face (alist-get 'description case)
                         (alist-get 'content case)
                         (alist-get 'check case))))

(ert-deftest test-terraform-mode--negation ()
  (dolist (case '(((description . "! before word gets builtin face inside resource block")
                   (content     . "resource \"r\" \"n\" {\n!var.enabled\n}")
                   (check       . (((pos . 20) (face . font-lock-builtin-face)))))
                  ((description . "! before paren gets builtin face inside resource block")
                   (content     . "resource \"r\" \"n\" {\n!(a || b)\n}")
                   (check       . (((pos . 20) (face . font-lock-builtin-face)))))
                  ((description . "! in != does not get builtin face")
                   (content     . "resource \"r\" \"n\" {\na != b\n}")
                   (check       . (((pos . 22) (face . nil)))))
                  ((description . "! alone does not get builtin face")
                   (content     . "resource \"r\" \"n\" {\n!\n}")
                   (check       . (((pos . 20) (face . nil)))))
                  ((description . "! outside any block gets no face")
                   (content     . "!var.enabled")
                   (check       . (((pos . 1) (face . nil)))))))
    (terraform-test-face (alist-get 'description case)
                         (alist-get 'content case)
                         (alist-get 'check case))))

(ert-deftest test-terraform-mode--dynamic-block ()
  (dolist (case '(((description . "dynamic keyword gets builtin face inside resource block")
                   (content     . "resource \"aws_instance\" \"foo\" {\ndynamic \"network_interface\" {\n}\n}")
                   (check       . (((pos . 33) (face . font-lock-builtin-face)))))
                  ((description . "dynamic label gets variable-name face inside resource block")
                   (content     . "resource \"aws_instance\" \"foo\" {\ndynamic \"network_interface\" {\n}\n}")
                   (check       . (((pos . 42) (face . font-lock-variable-name-face)))))
                  ((description . "content keyword gets builtin face inside dynamic block")
                   (content     . "resource \"aws_instance\" \"foo\" {\ndynamic \"network_interface\" {\ncontent {\n}\n}\n}")
                   (check       . (((pos . 63) (face . font-lock-builtin-face)))))))
    (terraform-test-face (alist-get 'description case)
                         (alist-get 'content case)
                         (alist-get 'check case))))

(ert-deftest test-terraform-mode--resource-builtins ()
  (dolist (case '(((description . "for_each gets builtin face inside resource block")
                   (content     . "resource \"aws_instance\" \"foo\" {\nfor_each = {}\n}")
                   (check       . (((pos . 33) (face . font-lock-builtin-face)))))
                  ((description . "count gets builtin face inside resource block")
                   (content     . "resource \"aws_instance\" \"foo\" {\ncount = 3\n}")
                   (check       . (((pos . 33) (face . font-lock-builtin-face)))))
                  ((description . "depends_on gets builtin face inside resource block")
                   (content     . "resource \"aws_instance\" \"foo\" {\ndepends_on = []\n}")
                   (check       . (((pos . 33) (face . font-lock-builtin-face)))))
                  ((description . "for_each outside resource block gets no face")
                   (content     . "for_each = {}")
                   (check       . (((pos . 1) (face . nil)))))))
    (terraform-test-face (alist-get 'description case)
                         (alist-get 'content case)
                         (alist-get 'check case))))

(ert-deftest test-terraform-mode--for-expression ()
  (dolist (case '(((description . "for keyword gets builtin face")
                   (content     . "[for val in list : val.id]")
                   (check       . (((pos . 2) (face . font-lock-builtin-face)))))
                  ((description . "in keyword gets builtin face")
                   (content     . "[for val in list : val.id]")
                   (check       . (((pos . 10) (face . font-lock-builtin-face)))))
                  ((description . "var declaration gets variable-name face")
                   (content     . "[for val in list : val.id]")
                   (check       . (((pos . 6) (face . font-lock-variable-name-face)))))
                  ((description . "var usage in body gets variable-name face")
                   (content     . "[for val in list : val.id]")
                   (check       . (((pos . 20) (face . font-lock-variable-name-face)))))
                  ((description . "first var in two-var form gets variable-name face")
                   (content     . "{for k, v in map : k => v}")
                   (check       . (((pos . 6) (face . font-lock-variable-name-face)))))
                  ((description . "second var in two-var form gets variable-name face")
                   (content     . "{for k, v in map : k => v}")
                   (check       . (((pos . 9) (face . font-lock-variable-name-face)))))
                  ((description . "first var body usage in two-var form gets variable-name face")
                   (content     . "{for k, v in map : k => v}")
                   (check       . (((pos . 20) (face . font-lock-variable-name-face)))))
                  ((description . "second var body usage in two-var form gets variable-name face")
                   (content     . "{for k, v in map : k => v}")
                   (check       . (((pos . 25) (face . font-lock-variable-name-face)))))
                  ((description . "for keyword gets builtin face in multi-line for expression")
                   (content     . "[\n  for log in list : log\n]")
                   (check       . (((pos . 5) (face . font-lock-builtin-face)))))
                  ((description . "in keyword gets builtin face in multi-line for expression")
                   (content     . "[\n  for log in list : log\n]")
                   (check       . (((pos . 13) (face . font-lock-builtin-face)))))
                  ((description . "var gets variable-name face in multi-line for expression")
                   (content     . "[\n  for log in list : log\n]")
                   (check       . (((pos . 9) (face . font-lock-variable-name-face)))))))
    (terraform-test-face (alist-get 'description case)
                         (alist-get 'content case)
                         (alist-get 'check case))))

(ert-deftest test-terraform-mode--for-expression-text-properties ()
  (dolist (case '(((description . "for expression region gets terraform-mode-for-expression property")
                   (content     . "[for val in list : val.id]")
                   (checks      . (((pos . 1) (property . terraform-mode-for-expression) (value . t)))))
                  ((description . "var declaration gets terraform-mode-for-var property")
                   (content     . "[for val in list : val.id]")
                   (checks      . (((pos . 6) (property . terraform-mode-for-var) (value . t)))))
                  ((description . "var body usage gets terraform-mode-for-var property")
                   (content     . "[for val in list : val.id]")
                   (checks      . (((pos . 20) (property . terraform-mode-for-var) (value . t)))))))
    (terraform-test-text-property (alist-get 'description case)
                                  (alist-get 'content case)
                                  (alist-get 'checks case))))

(defun terraform-test-indent (description content line expected-indent)
  "Assert that LINE in CONTENT indents to EXPECTED-INDENT.
LINE is 1-based.  DESCRIPTION is used in failure messages."
  (with-temp-buffer
    (terraform-mode)
    (insert content)
    (goto-char (point-min))
    (forward-line (1- line))
    (terraform-mode--indent-line)
    (let ((actual (current-indentation)))
      (unless (= actual expected-indent)
        (ert-fail (format "%s: line %d expected indent %d, got %d"
                          description line expected-indent actual))))))

;;; Indentation

(ert-deftest test-terraform-mode--indent ()
  (dolist (case '(((description . "top-level resource line indents to 0")
                   (content     . "resource \"aws_instance\" \"web\" {\n  ami = \"abc\"\n}\n")
                   (line        . 1)
                   (indent      . 0))
                  ((description . "content inside block indents to 2")
                   (content     . "resource \"aws_instance\" \"web\" {\n  ami = \"abc\"\n}\n")
                   (line        . 2)
                   (indent      . 2))
                  ((description . "closing brace indents to 0")
                   (content     . "resource \"aws_instance\" \"web\" {\n  ami = \"abc\"\n}\n")
                   (line        . 3)
                   (indent      . 0))
                  ((description . "second assignment line does not accumulate extra indent")
                   (content     . "resource \"aws_instance\" \"web\" {\n  ami = \"abc\"\n  instance_type = \"t3.micro\"\n}\n")
                   (line        . 3)
                   (indent      . 2))
                  ((description . "nested block closing brace indents to 2")
                   (content     . "resource \"aws_instance\" \"web\" {\n  provisioner \"local-exec\" {\n    command = \"echo hi\"\n  }\n}\n")
                   (line        . 4)
                   (indent      . 2))
                  ((description . "content inside nested block indents to 4")
                   (content     . "resource \"aws_instance\" \"web\" {\n  provisioner \"local-exec\" {\n    command = \"echo hi\"\n  }\n}\n")
                   (line        . 3)
                   (indent      . 4))))
    (terraform-test-indent (alist-get 'description case)
                           (alist-get 'content case)
                           (alist-get 'line case)
                           (alist-get 'indent case))))

(provide 'terraform-mode-test)
;;; terraform-mode-test.el ends here
